import { AxiosInstance } from 'axios';
import { AppResponse, AppRequest, AppSecretResponse, AppSessionResponse, AppPropertyResponse } from './types/app';
import { buildClient } from './utils/client';

// TODO add app api for developer document
// https://developers.mixin.one/
export const AppKeystoreClient = (axiosInstance: AxiosInstance) => ({
  // Get user's app share list
  favorites: (userID: string): Promise<AppResponse[]> => axiosInstance.get<unknown, AppResponse[]>(`/users/${userID}/apps/favorite`),

  // Update app setting
  update: (appID: string, params: AppRequest): Promise<AppResponse> => axiosInstance.post<unknown, AppResponse>(`/apps/${appID}`, params),

  // Add to your share list
  favorite: (appID: string): Promise<AppResponse[]> => axiosInstance.post<unknown, AppResponse[]>(`/apps/${appID}/favorite`),

  // Removing from your share list
  unfavorite: (appID: string): Promise<any> => axiosInstance.post<unknown, any>(`/apps/${appID}/unfavorite`),

  // Create a new app, 2 free credit for each user
  create: (params: AppRequest): Promise<AppResponse> => axiosInstance.post<unknown, AppResponse>(`/apps`, params),

  // Get a new app secret
  updateSecret: (appID: string): Promise<AppSecretResponse> => axiosInstance.post<unknown, AppSecretResponse>(`/apps/${appID}/secret`),

  // Get a new app session
  // pin is a string with 6-digit number, first digit cannot be 0
  // session_secret is generated by ed25519 public key
  updateSession: (appID: string, pin: string, session_secret: string): Promise<AppSessionResponse> => {
    const data = {
      pin,
      session_secret
    };
    return axiosInstance.post<unknown, AppSessionResponse>(`/apps/${appID}/session`, data);
  },

  // Get app list of current user
  fetchList: (): Promise<AppResponse[]> => axiosInstance.get<unknown, AppResponse[]>(`/apps`),

  // Get app number of current user and the price to buy new credit
  properties: (): Promise<AppPropertyResponse> => axiosInstance.get<unknown, AppPropertyResponse>(`/apps/property`),
});

export const AppClient = buildClient(AppKeystoreClient);

export default AppClient;