import { AxiosInstance } from 'axios';
import { AppResponse, AppPropertyResponse, AppRequest, AppSecretResponse, AppSessionResponse } from './types/app';
import { buildClient } from './utils/client';

// TODO add app api for developer document
/**
 * API for mixin users and official app
 * Notes:
 * * Some api only available for mixin official app
 * * Each Mixin user can only create two free apps
 * https://developers.mixin.one/
 */
export const AppKeystoreClient = (axiosInstance: AxiosInstance) => ({
  /** Get information of current user's a specific app */
  fetch: (appID: string): Promise<AppResponse> => axiosInstance.get<unknown, AppResponse>(`/apps/${appID}`),

  /**
   * Get app list of current user
   * Available for mixin official developer app only
   */
  fetchList: (): Promise<AppResponse[]> => axiosInstance.get<unknown, AppResponse[]>(`/apps`),

  /**
   * Get app number of current user and the price to buy new credit
   * Available for mixin official developer app only
   */
  properties: (): Promise<AppPropertyResponse> => axiosInstance.get<unknown, AppPropertyResponse>(`/apps/property`),

  /** Get user's app share list */
  favorites: (userID: string): Promise<AppResponse[]> => axiosInstance.get<unknown, AppResponse[]>(`/users/${userID}/apps/favorite`),

  /** Developer can create up to 2 free apps, or pay for more unlimited apps */
  create: (params: AppRequest): Promise<AppResponse> => axiosInstance.post<unknown, AppResponse>(`/apps`, params),

  /** Update app setting */
  update: (appID: string, params: AppRequest): Promise<AppResponse> => axiosInstance.post<unknown, AppResponse>(`/apps/${appID}`, params),

  /** Get a new app secret */
  updateSecret: (appID: string): Promise<AppSecretResponse> => axiosInstance.post<unknown, AppSecretResponse>(`/apps/${appID}/secret`),

  /**
   * Get a new app session
   * pin is a string with 6-digit number, first digit cannot be 0
   * session_secret is generated by ed25519 public key
   */
  updateSession: (appID: string, pin: string, session_secret: string): Promise<AppSessionResponse> => {
    const data = {
      pin,
      session_secret,
    };
    return axiosInstance.post<unknown, AppSessionResponse>(`/apps/${appID}/session`, data);
  },

  /**
   * Add to your share list
   * User can have up to 3 favorite apps
   */
  favorite: (appID: string): Promise<AppResponse[]> => axiosInstance.post<unknown, AppResponse[]>(`/apps/${appID}/favorite`),

  /** Removing from your share list */
  unfavorite: (appID: string): Promise<any> => axiosInstance.post<unknown, any>(`/apps/${appID}/unfavorite`),
});

export const AppClient = buildClient(AppKeystoreClient);

export default AppClient;
